# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: PyInstaller Windows
      # You may pin to the exact commit or the version.
      # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        # Directory containing source code (optional requirements.txt).
        path: . # default is src
        # Specify a custom URL for PYPI
        pypi_url: https://pypi.python.org/ # optional, default is https://pypi.python.org/
        # Specify a custom URL for PYPI Index
        pypi_index_url: https://pypi.python.org/simple # optional, default is https://pypi.python.org/simple
        # Specify a file path for .spec file
        spec: build.spec # optional, default i
